mutation Activate($data: ActivationData!) {
  activate(data: $data) {
    id
    createdAt
    updatedAt
    customer {
      id
      createdAt
      updatedAt
      email
      role
    }
    customerActivationCode
  }
}
